### ISSUE TITLE
Glyph vertical alignment issues

### ISSUE THREAD

**Issue by DMartinek** [felixmariotto/three-mesh-ui#161] opened 2022-02-14 12:48 UTC
Hi everyone!

First thanks for your great work on this library it really helps a lot when developing UIs in VR.
Unfortunately I hit an issue related to fonts. It seems that for some fonts the glyph positioning/metrics aren't correct. The json files generated by the [online converter](https://msdf-bmfont.donmccurdy.com/) seems to be fine (I also tested it with some of the offline tools, but get the same issues). In my case the error happens with the IBM Plex font but I was able to replicate it with Open Sans too. 

It seems that glyphs aren't correctly aligned vertically (and also the horizontal and line advances seem too big).:
![image](https://user-images.githubusercontent.com/8817287/153864071-27501694-5b94-4f41-b87d-ef62558286c4.png)

This is the same application using the online converters default font (yahei), which doesn't exhibit the issues:
![image](https://user-images.githubusercontent.com/8817287/153864284-320523cf-f131-4894-936e-37019bd64b00.png)

I also tried various options (like kerning/no kerning) etc. but nothing seems to help. The preview of the fonts in the online conversion tool also displays the font correctly.

Did someone else experience something similar? Is it possible that there is some user error on my part, or could there be an error in the libraries font handling?

**Comment by swingingtom** [comment] 2022-02-14 14:44
Hello @DMartinek , AFAIK this is indeed possible to notice some glyphs vertically mislocated, but this is per glyph only.
![image](https://user-images.githubusercontent.com/17314210/153877678-9658cef0-c2e1-4a02-a18c-b0a5f706c972.png)
( "i" and other characters are slightly above the baseline )

I've reexported YaHei from the same online converter. 
![image](https://user-images.githubusercontent.com/17314210/153884381-7e885acf-4858-4f60-8936-fe3347b26f18.png)
I can also notice the "i" and "s" above the baseline.

In the provided pictures, we can notice that the whole text is progressively offseting itself. And that Im currently not able to reproduce. At first sight, it might look like the camera perspective deformation, or the text or one of its parent has a slight rotation. Try to place the text in front of the camera to see if it can help.

**Comment by DMartinek** [comment] 2022-02-14 15:27
Hi @swingingtom, 

thanks for trying to replicate this. Yeah sorry the provided pictures were directly from an application with a perspective camera that's maybe why it seems to get worse over time. 

![image](https://user-images.githubusercontent.com/8817287/153890946-40643203-dd4d-4195-be02-a7678cae8c3b.png)

I've added some lines to show the issue more clearly. Some glyphs that descend below the base line like the 'g' seem to be offset a lot more than others.

It also seems strange that the line height seems to be wrong with that font while it works fine with others:
![image](https://user-images.githubusercontent.com/8817287/153892073-6cbc2358-57cc-459c-aa9b-683ef41dfafe.png)

I'm not sure if it is allowed to directly share bitmapfonts due to licensing so I rather not post the files here but I can send them to whoever is interested in replicating the behavior. You can also simply get the font from https://github.com/IBM/plex (I use the sans regular version) and use the online msdf converter to convert it using the following characters:
`azertyuiopqsdfghjklmwxcvbnAZERTYUIOPQSDFGHJKLMWXCVBN/\*-–+7894561230,;:!?.%$£€={}()[]&~"'#_|°@АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯяüÜöÖäÄñÑςερτυθιοπασδφγηξκλζχψωβνμΕΡΤΥΘΙΟΠΑΣΔΦΓΗΞΚΛΖΧΨΩΒΝΜåÅæÆøØ™©®`

**Comment by swingingtom** [comment] 2022-02-14 16:45
This could indeed comes from the library, and is intensified by a specific font.

Some toughts were I could be totally wrong
_Exported fonts are usually in with a font size of 42. Where 48 might be more divisible. Size are also usually exported in integers, so some precision could be lost/rounded during the process._

@felixmariotto do you have leads on this? I noticed that `anchor` is no more used. Is that a lead?

**Comment by felixmariotto** [comment] 2022-02-14 16:56
@swingingtom `anchor` is used [here](https://github.com/felixmariotto/three-mesh-ui/blob/35a7f0630633db3f28fea6c50c09e23f5287e618/src/content/MSDFGlyph.js#L122). It's computed [here](https://github.com/felixmariotto/three-mesh-ui/blob/35a7f0630633db3f28fea6c50c09e23f5287e618/src/content/MSDFText.js#L54) from the font JSON, honestly I'm not sure what could be wrong.. It would be interesting to use the generated files in another tool, to see if the problem comes from upstream.

**Comment by DMartinek** [comment] 2022-02-14 17:50
Hi,

I actually just had the same Idea 15 min ago and tried to use my font in A-frame (had the same issues with the spaces...). It seems that they render the font fine:
![image](https://user-images.githubusercontent.com/8817287/153918140-43306b70-acd1-475d-9984-06616299dfa9.png)

I will try to add my font to the codepen to see a direct comparison.

**Comment by swingingtom** [comment] 2022-02-16 19:05
> @swingingtom anchor is used [here](https://github.com/felixmariotto/three-mesh-ui/blob/35a7f0630633db3f28fea6c50c09e23f5287e618/src/content/MSDFGlyph.js#L122). It's computed [here](https://github.com/felixmariotto/three-mesh-ui/blob/35a7f0630633db3f28fea6c50c09e23f5287e618/src/content/MSDFText.js#L54) from the font JSON, honestly I'm not sure what could be wrong.. It would be interesting to use the generated files in another tool, to see if the problem comes from upstream.

my bad. sorry.

I did some export from command line. Font size 48, with 2 decimals. Nothing really helped :/

**Comment by swingingtom** [comment] 2022-09-06 14:05
Whereas not being able to identify the origin of this issue, 7.x.x would contain a tool to help us to fix those disagreement : https://felixmariotto.github.io/three-mesh-ui/7.x.x/#ex__baseline

**Comment by ROBYER1** [comment] 2022-10-11 10:16
From the issue mention, I am having similar issues with this font attached 
[Saira_Condensed-SemiBold-msdf.zip](https://github.com/felixmariotto/three-mesh-ui/files/9754070/Saira_Condensed-SemiBold-msdf.zip)

See comparison between the MSDF converter and three-mesh-ui
![unknown](https://user-images.githubusercontent.com/10745594/195064462-9fdee9e4-286f-4153-80b5-cca387909d36.png)

![unknown (1)](https://user-images.githubusercontent.com/10745594/195064498-2748ea28-b4a4-4d0b-bb3d-6e1ea91cd118.png)

**Comment by swingingtom** [comment] 2023-01-21 10:52
This has been fixed on v6.5.3
Alignment on msdf exported font are from top.

The result can be seen here https://codesandbox.io/s/glyphs-vertical-issues-vunz9
By switching three-mesh-ui version from v6.5.3 to v6.5.2 we can see vertical alignment respected.

Rye font is pretty handy as it has "matching spikes"
Not aligned (6.5.2)
![image](https://user-images.githubusercontent.com/17314210/213863147-39a010d7-910d-4430-99a0-38e6df79d380.png)
We can notice that spikes of "p" don't match other spikes.

Aligned (6.5.3)
![image](https://user-images.githubusercontent.com/17314210/213863184-0743f697-7f09-4d73-88bb-888802587606.png)
All spikes are aligned.

as @DMartinek said, it was especially noticeable with Saira font
![image](https://user-images.githubusercontent.com/17314210/213863523-82889241-8210-45bb-bccd-0c4fa1b21352.png)
![image](https://user-images.githubusercontent.com/17314210/213863566-6a08d264-4aa1-4730-9276-6df349180071.png)

We can also note a difference of character size.

Unfortunately, it doesn't fix alignment issues in Roboto.

**Closed by swingingtom** 2023-01-21 10:52 UTC
