### ISSUE TITLE
Updating quaternion of three-mesh-ui element

### ISSUE THREAD

**Issue by mhmtsrfglu** [felixmariotto/three-mesh-ui#54] opened 2020-12-18 13:50 UTC
Hello,

I want to update quaternion of item like Sprite or PlaneGeometry when I move my camera, is it possible ?
I tried  ` item.quaternion.copy(ctx.camera.quaternion)`. It works but half of item is losing.
![ss](https://user-images.githubusercontent.com/14332405/102622006-7a016400-4151-11eb-8a10-62bb9216e149.PNG)

Any correct way to do it ?

**Comment by felixmariotto** [comment] 2020-12-18 14:07
Hi !

I'm not sure I understand well what the problem is, according to my test you can totally rotate and set the quaternion of three-mesh-ui elements, see this fiddle : https://jsfiddle.net/felixmariotto/1n9sdyar/78/

Here is a basic fiddle which you can tweak to show me your issue : https://jsfiddle.net/felixmariotto/1n9sdyar/45/

**Comment by mhmtsrfglu** [comment] 2020-12-18 14:17
Hi again,

I have a 360 panorama picture and put a few hotspot in the panorama cube and I added info panels with mesh-ui next to hotspots.  I created my hotspots with PlaneGeometry  and I update quaternion of hotspots. When I move the camera and look to around of 360 picture, hotspots are looking my camera. I tried same for my mesh-ui and view looked like above picture.

**Comment by felixmariotto** [comment] 2020-12-18 14:27
Well as demonstrated in the fiddle above I can't reproduce any bug with setting quaternion of a three-mesh-ui element...
Maybe you could share a piece of code or a working fiddle demonstrating your issue ? Above I gave you the link to a template with three-mesh-ui set up, it should be easy to reproduce your problem with the camera.

**Comment by mhmtsrfglu** [comment] 2020-12-18 14:41
Below code for creating panels
```
const panels = [];
export function createInfoPanel(coordinates, texture, hotspot) {
    const container = new ThreeMeshUI.Block({
        height: 10,
        width: 10,
        backgroundOpacity: 0,
    });
    container.position.set(coordinates.x  coordinates.y  coordinates.z);

    const imageBlock = new ThreeMeshUI.Block({
        height: 20,
        width: 20,
    });

    const textBlock = new ThreeMeshUI.Block({
        height: 5,
        width: 20,
    });

    container.add(imageBlock, textBlock);
    container.parentComponent = hotspot;

    //
    const loader = new THREE.TextureLoader();

    loader.load(texture, (texture) => {
        imageBlock.set({backgroundTexture: texture});
    });

    //

    container.set({
        fontFamily: require('../fonts/Roboto-msdf.json'),
        fontTexture: require('../fonts/Roboto-msdf.png').default,
    });


    const text = new ThreeMeshUI.Text({
        content: hotspot.name
    });

    textBlock.add(text);

    //

    text.set({
        fontColor: new THREE.Color(0xd2ffbd),
        fontSize: 2,
    });
    panels.push(container);
}
```
and render code.

```
function render() {
    ThreeMeshUI.update();
   panels.forEach(item => {
            item.quaternion.copy(camera.quaternion);
        })
    renderer.render(scene, camera)
}
```

and different camera views when I move. Problem,  half some part of panel is losing for every move. I am sorry code is little big and could not implement again on fiddle.

![1](https://user-images.githubusercontent.com/14332405/102626321-b6d05980-4157-11eb-99ac-b2ebfcdd98e8.PNG)

![2](https://user-images.githubusercontent.com/14332405/102626330-b932b380-4157-11eb-8bc7-63f13f1c17c1.PNG)

![3](https://user-images.githubusercontent.com/14332405/102626673-2e05ed80-4158-11eb-8c29-0a0f8df62e9a.PNG)

**Comment by felixmariotto** [comment] 2020-12-18 14:56
I've made a fiddle with one one panel updating according to the camera's quaternion and one fixed : https://jsfiddle.net/felixmariotto/7xk6wa9s/9/

It's the expected behavior... I can't reproduce.
Would you please share a video of the issue ? It may give some clues...

**Comment by felixmariotto** [comment] 2020-12-18 14:59
wait is that for VR ?

**Comment by mhmtsrfglu** [comment] 2020-12-22 08:34
Hi, yes it is for VR, 
I still couldn't resolve my problem, here is a live example: https://meshuiexample.surge.sh/

**Comment by felixmariotto** [comment] 2020-12-22 17:07
I've updated my fiddle to replicate what your setup looks like : [https://jsfiddle.net/felixmariotto/7xk6wa9s/35/](https://jsfiddle.net/felixmariotto/7xk6wa9s/35/)

Seems to work, it's hard to say what's different in your minified code.

Possibly an issue with the camera far plane... What are your camera near and far planes values ?

**Comment by felixmariotto** [comment] 2020-12-22 18:45
is your camera a child of any object with modified position rotation or scale ?
How do you move the camera around ?

**Comment by mhmtsrfglu** [comment] 2020-12-24 14:33
is your camera a child of any object with modified position rotation or scale ? -> No, I am moving camera with orbit controller.

I solved the problem. I was only updating the quaternion of item, I updated position based parent position and quaternion based parent quaternion together on render method.

**Comment by felixmariotto** [comment] 2020-12-24 16:08
Ok glad you fixed it !
I'm closing, feel free to reach out if you have another issue.

**Closed by felixmariotto** 2020-12-24 16:08 UTC
